apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-read-write
  namespace: {{ include "common.names.namespace" . | quote }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "create"]