# Temporarily here until https://github.com/agentic-community/mcp-gateway-registry/issues/234 is addressed
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
{{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.podLabels .Values.commonLabels) "context" .) }}
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" .) | nindent 4 }}
  type: ClusterIP
  internalTrafficPolicy: Cluster
